# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hyperspace.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hyperspace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hyperspace.proto\x12\nhyperspace\"\x97\x01\n\rInsertRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x01\x12\n\n\x02id\x18\x02 \x01(\r\x12\x39\n\x08metadata\x18\x03 \x03(\x0b\x32\'.hyperspace.InsertRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x0eInsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x94\x01\n\rSearchRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x01\x12\r\n\x05top_k\x18\x02 \x01(\r\x12\x35\n\x06\x66ilter\x18\x03 \x03(\x0b\x32%.hyperspace.SearchRequest.FilterEntry\x1a-\n\x0b\x46ilterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x0eSearchResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.hyperspace.SearchResult\",\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\"\x10\n\x0eMonitorRequest\"I\n\x0bSystemStats\x12\x17\n\x0findexed_vectors\x18\x01 \x01(\x04\x12\x14\n\x0cram_usage_mb\x18\x02 \x01(\x01\x12\x0b\n\x03qps\x18\x03 \x01(\x01\x32\xce\x01\n\x08\x44\x61tabase\x12?\n\x06Insert\x12\x19.hyperspace.InsertRequest\x1a\x1a.hyperspace.InsertResponse\x12?\n\x06Search\x12\x19.hyperspace.SearchRequest\x1a\x1a.hyperspace.SearchResponse\x12@\n\x07Monitor\x12\x1a.hyperspace.MonitorRequest\x1a\x17.hyperspace.SystemStats0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hyperspace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_INSERTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST_FILTERENTRY']._loaded_options = None
  _globals['_SEARCHREQUEST_FILTERENTRY']._serialized_options = b'8\001'
  _globals['_INSERTREQUEST']._serialized_start=33
  _globals['_INSERTREQUEST']._serialized_end=184
  _globals['_INSERTREQUEST_METADATAENTRY']._serialized_start=137
  _globals['_INSERTREQUEST_METADATAENTRY']._serialized_end=184
  _globals['_INSERTRESPONSE']._serialized_start=186
  _globals['_INSERTRESPONSE']._serialized_end=219
  _globals['_SEARCHREQUEST']._serialized_start=222
  _globals['_SEARCHREQUEST']._serialized_end=370
  _globals['_SEARCHREQUEST_FILTERENTRY']._serialized_start=325
  _globals['_SEARCHREQUEST_FILTERENTRY']._serialized_end=370
  _globals['_SEARCHRESPONSE']._serialized_start=372
  _globals['_SEARCHRESPONSE']._serialized_end=431
  _globals['_SEARCHRESULT']._serialized_start=433
  _globals['_SEARCHRESULT']._serialized_end=477
  _globals['_MONITORREQUEST']._serialized_start=479
  _globals['_MONITORREQUEST']._serialized_end=495
  _globals['_SYSTEMSTATS']._serialized_start=497
  _globals['_SYSTEMSTATS']._serialized_end=570
  _globals['_DATABASE']._serialized_start=573
  _globals['_DATABASE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
