[package]
name = "hyperspace-embed"
version = "3.1.3"
edition = "2021"
description = "Universal Embedding Wrapper for HyperspaceDB (Local ONNX + Remote APIs)"

[dependencies]
ort = { workspace = true } 
tokenizers = { workspace = true }
ndarray = { workspace = true }

anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] } # Required for API support
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hf-hub = { workspace = true }
libloading = "0.9"

[features]
default = []
