# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hyperspace_pb2 as hyperspace__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hyperspace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/hyperspace.Database/CreateCollection',
                request_serializer=hyperspace__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/hyperspace.Database/DeleteCollection',
                request_serializer=hyperspace__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/hyperspace.Database/ListCollections',
                request_serializer=hyperspace__pb2.Empty.SerializeToString,
                response_deserializer=hyperspace__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.GetCollectionStats = channel.unary_unary(
                '/hyperspace.Database/GetCollectionStats',
                request_serializer=hyperspace__pb2.CollectionStatsRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.CollectionStatsResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/hyperspace.Database/Insert',
                request_serializer=hyperspace__pb2.InsertRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.BatchInsert = channel.unary_unary(
                '/hyperspace.Database/BatchInsert',
                request_serializer=hyperspace__pb2.BatchInsertRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.InsertText = channel.unary_unary(
                '/hyperspace.Database/InsertText',
                request_serializer=hyperspace__pb2.InsertTextRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/hyperspace.Database/Delete',
                request_serializer=hyperspace__pb2.DeleteRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/hyperspace.Database/Search',
                request_serializer=hyperspace__pb2.SearchRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Monitor = channel.unary_stream(
                '/hyperspace.Database/Monitor',
                request_serializer=hyperspace__pb2.MonitorRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.SystemStats.FromString,
                _registered_method=True)
        self.TriggerSnapshot = channel.unary_unary(
                '/hyperspace.Database/TriggerSnapshot',
                request_serializer=hyperspace__pb2.Empty.SerializeToString,
                response_deserializer=hyperspace__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.TriggerVacuum = channel.unary_unary(
                '/hyperspace.Database/TriggerVacuum',
                request_serializer=hyperspace__pb2.Empty.SerializeToString,
                response_deserializer=hyperspace__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/hyperspace.Database/Configure',
                request_serializer=hyperspace__pb2.ConfigUpdate.SerializeToString,
                response_deserializer=hyperspace__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Replicate = channel.unary_stream(
                '/hyperspace.Database/Replicate',
                request_serializer=hyperspace__pb2.Empty.SerializeToString,
                response_deserializer=hyperspace__pb2.ReplicationLog.FromString,
                _registered_method=True)
        self.GetDigest = channel.unary_unary(
                '/hyperspace.Database/GetDigest',
                request_serializer=hyperspace__pb2.DigestRequest.SerializeToString,
                response_deserializer=hyperspace__pb2.DigestResponse.FromString,
                _registered_method=True)


class DatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCollection(self, request, context):
        """Collection Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Insert vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search (ANN)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Monitor(self, request, context):
        """Stream statistics for TUI (Global or Collection tailored)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSnapshot(self, request, context):
        """Admin Controls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerVacuum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Dynamic Configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request, context):
        """Replication (Leader -> Follower)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDigest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=hyperspace__pb2.CreateCollectionRequest.FromString,
                    response_serializer=hyperspace__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=hyperspace__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=hyperspace__pb2.StatusResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=hyperspace__pb2.Empty.FromString,
                    response_serializer=hyperspace__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'GetCollectionStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionStats,
                    request_deserializer=hyperspace__pb2.CollectionStatsRequest.FromString,
                    response_serializer=hyperspace__pb2.CollectionStatsResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=hyperspace__pb2.InsertRequest.FromString,
                    response_serializer=hyperspace__pb2.InsertResponse.SerializeToString,
            ),
            'BatchInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsert,
                    request_deserializer=hyperspace__pb2.BatchInsertRequest.FromString,
                    response_serializer=hyperspace__pb2.InsertResponse.SerializeToString,
            ),
            'InsertText': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertText,
                    request_deserializer=hyperspace__pb2.InsertTextRequest.FromString,
                    response_serializer=hyperspace__pb2.InsertResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=hyperspace__pb2.DeleteRequest.FromString,
                    response_serializer=hyperspace__pb2.DeleteResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=hyperspace__pb2.SearchRequest.FromString,
                    response_serializer=hyperspace__pb2.SearchResponse.SerializeToString,
            ),
            'Monitor': grpc.unary_stream_rpc_method_handler(
                    servicer.Monitor,
                    request_deserializer=hyperspace__pb2.MonitorRequest.FromString,
                    response_serializer=hyperspace__pb2.SystemStats.SerializeToString,
            ),
            'TriggerSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSnapshot,
                    request_deserializer=hyperspace__pb2.Empty.FromString,
                    response_serializer=hyperspace__pb2.StatusResponse.SerializeToString,
            ),
            'TriggerVacuum': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerVacuum,
                    request_deserializer=hyperspace__pb2.Empty.FromString,
                    response_serializer=hyperspace__pb2.StatusResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=hyperspace__pb2.ConfigUpdate.FromString,
                    response_serializer=hyperspace__pb2.StatusResponse.SerializeToString,
            ),
            'Replicate': grpc.unary_stream_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=hyperspace__pb2.Empty.FromString,
                    response_serializer=hyperspace__pb2.ReplicationLog.SerializeToString,
            ),
            'GetDigest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDigest,
                    request_deserializer=hyperspace__pb2.DigestRequest.FromString,
                    response_serializer=hyperspace__pb2.DigestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperspace.Database', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperspace.Database', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Database(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/CreateCollection',
            hyperspace__pb2.CreateCollectionRequest.SerializeToString,
            hyperspace__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/DeleteCollection',
            hyperspace__pb2.DeleteCollectionRequest.SerializeToString,
            hyperspace__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/ListCollections',
            hyperspace__pb2.Empty.SerializeToString,
            hyperspace__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/GetCollectionStats',
            hyperspace__pb2.CollectionStatsRequest.SerializeToString,
            hyperspace__pb2.CollectionStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/Insert',
            hyperspace__pb2.InsertRequest.SerializeToString,
            hyperspace__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/BatchInsert',
            hyperspace__pb2.BatchInsertRequest.SerializeToString,
            hyperspace__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/InsertText',
            hyperspace__pb2.InsertTextRequest.SerializeToString,
            hyperspace__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/Delete',
            hyperspace__pb2.DeleteRequest.SerializeToString,
            hyperspace__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/Search',
            hyperspace__pb2.SearchRequest.SerializeToString,
            hyperspace__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Monitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperspace.Database/Monitor',
            hyperspace__pb2.MonitorRequest.SerializeToString,
            hyperspace__pb2.SystemStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/TriggerSnapshot',
            hyperspace__pb2.Empty.SerializeToString,
            hyperspace__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerVacuum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/TriggerVacuum',
            hyperspace__pb2.Empty.SerializeToString,
            hyperspace__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/Configure',
            hyperspace__pb2.ConfigUpdate.SerializeToString,
            hyperspace__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hyperspace.Database/Replicate',
            hyperspace__pb2.Empty.SerializeToString,
            hyperspace__pb2.ReplicationLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDigest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperspace.Database/GetDigest',
            hyperspace__pb2.DigestRequest.SerializeToString,
            hyperspace__pb2.DigestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
