[package]
name = "hyperspace-proto"
version = "3.1.6"
edition = "2021"
description = "Protobuf definitions and generated gRPC code for HyperspaceDB"
license = "MIT"
repository = "https://github.com/yarlabs/hyperspacedb"

[dependencies]
tonic = "0.10"
prost = "0.12"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.10"
