// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hyperspace.proto

#include "hyperspace.pb.h"
#include "hyperspace.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace hyperspace {

static const char* Database_method_names[] = {
  "/hyperspace.Database/CreateCollection",
  "/hyperspace.Database/DeleteCollection",
  "/hyperspace.Database/ListCollections",
  "/hyperspace.Database/GetCollectionStats",
  "/hyperspace.Database/Insert",
  "/hyperspace.Database/BatchInsert",
  "/hyperspace.Database/InsertText",
  "/hyperspace.Database/Delete",
  "/hyperspace.Database/Search",
  "/hyperspace.Database/SearchBatch",
  "/hyperspace.Database/GetNode",
  "/hyperspace.Database/GetNeighbors",
  "/hyperspace.Database/GetConceptParents",
  "/hyperspace.Database/Traverse",
  "/hyperspace.Database/FindSemanticClusters",
  "/hyperspace.Database/Monitor",
  "/hyperspace.Database/TriggerSnapshot",
  "/hyperspace.Database/TriggerVacuum",
  "/hyperspace.Database/Configure",
  "/hyperspace.Database/Replicate",
  "/hyperspace.Database/SubscribeToEvents",
  "/hyperspace.Database/GetDigest",
  "/hyperspace.Database/RebuildIndex",
  "/hyperspace.Database/SyncHandshake",
  "/hyperspace.Database/SyncPull",
  "/hyperspace.Database/SyncPush",
};

std::unique_ptr< Database::Stub> Database::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Database::Stub> stub(new Database::Stub(channel, options));
  return stub;
}

Database::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateCollection_(Database_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteCollection_(Database_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListCollections_(Database_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCollectionStats_(Database_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Insert_(Database_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchInsert_(Database_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InsertText_(Database_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(Database_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Search_(Database_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchBatch_(Database_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNode_(Database_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNeighbors_(Database_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetConceptParents_(Database_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Traverse_(Database_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindSemanticClusters_(Database_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Monitor_(Database_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_TriggerSnapshot_(Database_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TriggerVacuum_(Database_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Configure_(Database_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Replicate_(Database_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SubscribeToEvents_(Database_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetDigest_(Database_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RebuildIndex_(Database_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SyncHandshake_(Database_method_names[23], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SyncPull_(Database_method_names[24], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SyncPush_(Database_method_names[25], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status Database::Stub::CreateCollection(::grpc::ClientContext* context, const ::hyperspace::CreateCollectionRequest& request, ::hyperspace::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::CreateCollectionRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateCollection_, context, request, response);
}

void Database::Stub::async::CreateCollection(::grpc::ClientContext* context, const ::hyperspace::CreateCollectionRequest* request, ::hyperspace::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::CreateCollectionRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCollection_, context, request, response, std::move(f));
}

void Database::Stub::async::CreateCollection(::grpc::ClientContext* context, const ::hyperspace::CreateCollectionRequest* request, ::hyperspace::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCollection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::PrepareAsyncCreateCollectionRaw(::grpc::ClientContext* context, const ::hyperspace::CreateCollectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::StatusResponse, ::hyperspace::CreateCollectionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateCollection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::AsyncCreateCollectionRaw(::grpc::ClientContext* context, const ::hyperspace::CreateCollectionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateCollectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::DeleteCollection(::grpc::ClientContext* context, const ::hyperspace::DeleteCollectionRequest& request, ::hyperspace::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::DeleteCollectionRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteCollection_, context, request, response);
}

void Database::Stub::async::DeleteCollection(::grpc::ClientContext* context, const ::hyperspace::DeleteCollectionRequest* request, ::hyperspace::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::DeleteCollectionRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteCollection_, context, request, response, std::move(f));
}

void Database::Stub::async::DeleteCollection(::grpc::ClientContext* context, const ::hyperspace::DeleteCollectionRequest* request, ::hyperspace::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteCollection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::PrepareAsyncDeleteCollectionRaw(::grpc::ClientContext* context, const ::hyperspace::DeleteCollectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::StatusResponse, ::hyperspace::DeleteCollectionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteCollection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::AsyncDeleteCollectionRaw(::grpc::ClientContext* context, const ::hyperspace::DeleteCollectionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteCollectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::ListCollections(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::hyperspace::ListCollectionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::Empty, ::hyperspace::ListCollectionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListCollections_, context, request, response);
}

void Database::Stub::async::ListCollections(::grpc::ClientContext* context, const ::hyperspace::Empty* request, ::hyperspace::ListCollectionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::Empty, ::hyperspace::ListCollectionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCollections_, context, request, response, std::move(f));
}

void Database::Stub::async::ListCollections(::grpc::ClientContext* context, const ::hyperspace::Empty* request, ::hyperspace::ListCollectionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCollections_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::ListCollectionsResponse>* Database::Stub::PrepareAsyncListCollectionsRaw(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::ListCollectionsResponse, ::hyperspace::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListCollections_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::ListCollectionsResponse>* Database::Stub::AsyncListCollectionsRaw(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListCollectionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::GetCollectionStats(::grpc::ClientContext* context, const ::hyperspace::CollectionStatsRequest& request, ::hyperspace::CollectionStatsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::CollectionStatsRequest, ::hyperspace::CollectionStatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCollectionStats_, context, request, response);
}

void Database::Stub::async::GetCollectionStats(::grpc::ClientContext* context, const ::hyperspace::CollectionStatsRequest* request, ::hyperspace::CollectionStatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::CollectionStatsRequest, ::hyperspace::CollectionStatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCollectionStats_, context, request, response, std::move(f));
}

void Database::Stub::async::GetCollectionStats(::grpc::ClientContext* context, const ::hyperspace::CollectionStatsRequest* request, ::hyperspace::CollectionStatsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCollectionStats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::CollectionStatsResponse>* Database::Stub::PrepareAsyncGetCollectionStatsRaw(::grpc::ClientContext* context, const ::hyperspace::CollectionStatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::CollectionStatsResponse, ::hyperspace::CollectionStatsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCollectionStats_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::CollectionStatsResponse>* Database::Stub::AsyncGetCollectionStatsRaw(::grpc::ClientContext* context, const ::hyperspace::CollectionStatsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCollectionStatsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::Insert(::grpc::ClientContext* context, const ::hyperspace::InsertRequest& request, ::hyperspace::InsertResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::InsertRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Insert_, context, request, response);
}

void Database::Stub::async::Insert(::grpc::ClientContext* context, const ::hyperspace::InsertRequest* request, ::hyperspace::InsertResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::InsertRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Insert_, context, request, response, std::move(f));
}

void Database::Stub::async::Insert(::grpc::ClientContext* context, const ::hyperspace::InsertRequest* request, ::hyperspace::InsertResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Insert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::InsertResponse>* Database::Stub::PrepareAsyncInsertRaw(::grpc::ClientContext* context, const ::hyperspace::InsertRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::InsertResponse, ::hyperspace::InsertRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Insert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::InsertResponse>* Database::Stub::AsyncInsertRaw(::grpc::ClientContext* context, const ::hyperspace::InsertRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInsertRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::BatchInsert(::grpc::ClientContext* context, const ::hyperspace::BatchInsertRequest& request, ::hyperspace::InsertResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::BatchInsertRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchInsert_, context, request, response);
}

void Database::Stub::async::BatchInsert(::grpc::ClientContext* context, const ::hyperspace::BatchInsertRequest* request, ::hyperspace::InsertResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::BatchInsertRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchInsert_, context, request, response, std::move(f));
}

void Database::Stub::async::BatchInsert(::grpc::ClientContext* context, const ::hyperspace::BatchInsertRequest* request, ::hyperspace::InsertResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchInsert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::InsertResponse>* Database::Stub::PrepareAsyncBatchInsertRaw(::grpc::ClientContext* context, const ::hyperspace::BatchInsertRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::InsertResponse, ::hyperspace::BatchInsertRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchInsert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::InsertResponse>* Database::Stub::AsyncBatchInsertRaw(::grpc::ClientContext* context, const ::hyperspace::BatchInsertRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchInsertRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::InsertText(::grpc::ClientContext* context, const ::hyperspace::InsertTextRequest& request, ::hyperspace::InsertResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::InsertTextRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InsertText_, context, request, response);
}

void Database::Stub::async::InsertText(::grpc::ClientContext* context, const ::hyperspace::InsertTextRequest* request, ::hyperspace::InsertResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::InsertTextRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InsertText_, context, request, response, std::move(f));
}

void Database::Stub::async::InsertText(::grpc::ClientContext* context, const ::hyperspace::InsertTextRequest* request, ::hyperspace::InsertResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InsertText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::InsertResponse>* Database::Stub::PrepareAsyncInsertTextRaw(::grpc::ClientContext* context, const ::hyperspace::InsertTextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::InsertResponse, ::hyperspace::InsertTextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InsertText_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::InsertResponse>* Database::Stub::AsyncInsertTextRaw(::grpc::ClientContext* context, const ::hyperspace::InsertTextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInsertTextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::Delete(::grpc::ClientContext* context, const ::hyperspace::DeleteRequest& request, ::hyperspace::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::DeleteRequest, ::hyperspace::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void Database::Stub::async::Delete(::grpc::ClientContext* context, const ::hyperspace::DeleteRequest* request, ::hyperspace::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::DeleteRequest, ::hyperspace::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void Database::Stub::async::Delete(::grpc::ClientContext* context, const ::hyperspace::DeleteRequest* request, ::hyperspace::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::DeleteResponse>* Database::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::hyperspace::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::DeleteResponse, ::hyperspace::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::DeleteResponse>* Database::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::hyperspace::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::Search(::grpc::ClientContext* context, const ::hyperspace::SearchRequest& request, ::hyperspace::SearchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::SearchRequest, ::hyperspace::SearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Search_, context, request, response);
}

void Database::Stub::async::Search(::grpc::ClientContext* context, const ::hyperspace::SearchRequest* request, ::hyperspace::SearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::SearchRequest, ::hyperspace::SearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, std::move(f));
}

void Database::Stub::async::Search(::grpc::ClientContext* context, const ::hyperspace::SearchRequest* request, ::hyperspace::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::SearchResponse>* Database::Stub::PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::hyperspace::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::SearchResponse, ::hyperspace::SearchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Search_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::SearchResponse>* Database::Stub::AsyncSearchRaw(::grpc::ClientContext* context, const ::hyperspace::SearchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSearchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::SearchBatch(::grpc::ClientContext* context, const ::hyperspace::BatchSearchRequest& request, ::hyperspace::BatchSearchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::BatchSearchRequest, ::hyperspace::BatchSearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SearchBatch_, context, request, response);
}

void Database::Stub::async::SearchBatch(::grpc::ClientContext* context, const ::hyperspace::BatchSearchRequest* request, ::hyperspace::BatchSearchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::BatchSearchRequest, ::hyperspace::BatchSearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchBatch_, context, request, response, std::move(f));
}

void Database::Stub::async::SearchBatch(::grpc::ClientContext* context, const ::hyperspace::BatchSearchRequest* request, ::hyperspace::BatchSearchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::BatchSearchResponse>* Database::Stub::PrepareAsyncSearchBatchRaw(::grpc::ClientContext* context, const ::hyperspace::BatchSearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::BatchSearchResponse, ::hyperspace::BatchSearchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SearchBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::BatchSearchResponse>* Database::Stub::AsyncSearchBatchRaw(::grpc::ClientContext* context, const ::hyperspace::BatchSearchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSearchBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::GetNode(::grpc::ClientContext* context, const ::hyperspace::GetNodeRequest& request, ::hyperspace::GraphNode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::GetNodeRequest, ::hyperspace::GraphNode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNode_, context, request, response);
}

void Database::Stub::async::GetNode(::grpc::ClientContext* context, const ::hyperspace::GetNodeRequest* request, ::hyperspace::GraphNode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::GetNodeRequest, ::hyperspace::GraphNode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNode_, context, request, response, std::move(f));
}

void Database::Stub::async::GetNode(::grpc::ClientContext* context, const ::hyperspace::GetNodeRequest* request, ::hyperspace::GraphNode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::GraphNode>* Database::Stub::PrepareAsyncGetNodeRaw(::grpc::ClientContext* context, const ::hyperspace::GetNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::GraphNode, ::hyperspace::GetNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::GraphNode>* Database::Stub::AsyncGetNodeRaw(::grpc::ClientContext* context, const ::hyperspace::GetNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::GetNeighbors(::grpc::ClientContext* context, const ::hyperspace::GetNeighborsRequest& request, ::hyperspace::GetNeighborsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::GetNeighborsRequest, ::hyperspace::GetNeighborsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNeighbors_, context, request, response);
}

void Database::Stub::async::GetNeighbors(::grpc::ClientContext* context, const ::hyperspace::GetNeighborsRequest* request, ::hyperspace::GetNeighborsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::GetNeighborsRequest, ::hyperspace::GetNeighborsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNeighbors_, context, request, response, std::move(f));
}

void Database::Stub::async::GetNeighbors(::grpc::ClientContext* context, const ::hyperspace::GetNeighborsRequest* request, ::hyperspace::GetNeighborsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNeighbors_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::GetNeighborsResponse>* Database::Stub::PrepareAsyncGetNeighborsRaw(::grpc::ClientContext* context, const ::hyperspace::GetNeighborsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::GetNeighborsResponse, ::hyperspace::GetNeighborsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNeighbors_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::GetNeighborsResponse>* Database::Stub::AsyncGetNeighborsRaw(::grpc::ClientContext* context, const ::hyperspace::GetNeighborsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNeighborsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::GetConceptParents(::grpc::ClientContext* context, const ::hyperspace::GetConceptParentsRequest& request, ::hyperspace::GetConceptParentsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::GetConceptParentsRequest, ::hyperspace::GetConceptParentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetConceptParents_, context, request, response);
}

void Database::Stub::async::GetConceptParents(::grpc::ClientContext* context, const ::hyperspace::GetConceptParentsRequest* request, ::hyperspace::GetConceptParentsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::GetConceptParentsRequest, ::hyperspace::GetConceptParentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConceptParents_, context, request, response, std::move(f));
}

void Database::Stub::async::GetConceptParents(::grpc::ClientContext* context, const ::hyperspace::GetConceptParentsRequest* request, ::hyperspace::GetConceptParentsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConceptParents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::GetConceptParentsResponse>* Database::Stub::PrepareAsyncGetConceptParentsRaw(::grpc::ClientContext* context, const ::hyperspace::GetConceptParentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::GetConceptParentsResponse, ::hyperspace::GetConceptParentsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetConceptParents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::GetConceptParentsResponse>* Database::Stub::AsyncGetConceptParentsRaw(::grpc::ClientContext* context, const ::hyperspace::GetConceptParentsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetConceptParentsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::Traverse(::grpc::ClientContext* context, const ::hyperspace::TraverseRequest& request, ::hyperspace::TraverseResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::TraverseRequest, ::hyperspace::TraverseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Traverse_, context, request, response);
}

void Database::Stub::async::Traverse(::grpc::ClientContext* context, const ::hyperspace::TraverseRequest* request, ::hyperspace::TraverseResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::TraverseRequest, ::hyperspace::TraverseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Traverse_, context, request, response, std::move(f));
}

void Database::Stub::async::Traverse(::grpc::ClientContext* context, const ::hyperspace::TraverseRequest* request, ::hyperspace::TraverseResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Traverse_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::TraverseResponse>* Database::Stub::PrepareAsyncTraverseRaw(::grpc::ClientContext* context, const ::hyperspace::TraverseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::TraverseResponse, ::hyperspace::TraverseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Traverse_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::TraverseResponse>* Database::Stub::AsyncTraverseRaw(::grpc::ClientContext* context, const ::hyperspace::TraverseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTraverseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::FindSemanticClusters(::grpc::ClientContext* context, const ::hyperspace::FindSemanticClustersRequest& request, ::hyperspace::FindSemanticClustersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::FindSemanticClustersRequest, ::hyperspace::FindSemanticClustersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindSemanticClusters_, context, request, response);
}

void Database::Stub::async::FindSemanticClusters(::grpc::ClientContext* context, const ::hyperspace::FindSemanticClustersRequest* request, ::hyperspace::FindSemanticClustersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::FindSemanticClustersRequest, ::hyperspace::FindSemanticClustersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindSemanticClusters_, context, request, response, std::move(f));
}

void Database::Stub::async::FindSemanticClusters(::grpc::ClientContext* context, const ::hyperspace::FindSemanticClustersRequest* request, ::hyperspace::FindSemanticClustersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindSemanticClusters_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::FindSemanticClustersResponse>* Database::Stub::PrepareAsyncFindSemanticClustersRaw(::grpc::ClientContext* context, const ::hyperspace::FindSemanticClustersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::FindSemanticClustersResponse, ::hyperspace::FindSemanticClustersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindSemanticClusters_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::FindSemanticClustersResponse>* Database::Stub::AsyncFindSemanticClustersRaw(::grpc::ClientContext* context, const ::hyperspace::FindSemanticClustersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindSemanticClustersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::hyperspace::SystemStats>* Database::Stub::MonitorRaw(::grpc::ClientContext* context, const ::hyperspace::MonitorRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hyperspace::SystemStats>::Create(channel_.get(), rpcmethod_Monitor_, context, request);
}

void Database::Stub::async::Monitor(::grpc::ClientContext* context, const ::hyperspace::MonitorRequest* request, ::grpc::ClientReadReactor< ::hyperspace::SystemStats>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hyperspace::SystemStats>::Create(stub_->channel_.get(), stub_->rpcmethod_Monitor_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hyperspace::SystemStats>* Database::Stub::AsyncMonitorRaw(::grpc::ClientContext* context, const ::hyperspace::MonitorRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::SystemStats>::Create(channel_.get(), cq, rpcmethod_Monitor_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hyperspace::SystemStats>* Database::Stub::PrepareAsyncMonitorRaw(::grpc::ClientContext* context, const ::hyperspace::MonitorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::SystemStats>::Create(channel_.get(), cq, rpcmethod_Monitor_, context, request, false, nullptr);
}

::grpc::Status Database::Stub::TriggerSnapshot(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::hyperspace::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::Empty, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TriggerSnapshot_, context, request, response);
}

void Database::Stub::async::TriggerSnapshot(::grpc::ClientContext* context, const ::hyperspace::Empty* request, ::hyperspace::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::Empty, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TriggerSnapshot_, context, request, response, std::move(f));
}

void Database::Stub::async::TriggerSnapshot(::grpc::ClientContext* context, const ::hyperspace::Empty* request, ::hyperspace::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TriggerSnapshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::PrepareAsyncTriggerSnapshotRaw(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::StatusResponse, ::hyperspace::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TriggerSnapshot_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::AsyncTriggerSnapshotRaw(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTriggerSnapshotRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::TriggerVacuum(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::hyperspace::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::Empty, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TriggerVacuum_, context, request, response);
}

void Database::Stub::async::TriggerVacuum(::grpc::ClientContext* context, const ::hyperspace::Empty* request, ::hyperspace::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::Empty, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TriggerVacuum_, context, request, response, std::move(f));
}

void Database::Stub::async::TriggerVacuum(::grpc::ClientContext* context, const ::hyperspace::Empty* request, ::hyperspace::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TriggerVacuum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::PrepareAsyncTriggerVacuumRaw(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::StatusResponse, ::hyperspace::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TriggerVacuum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::AsyncTriggerVacuumRaw(::grpc::ClientContext* context, const ::hyperspace::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTriggerVacuumRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::Configure(::grpc::ClientContext* context, const ::hyperspace::ConfigUpdate& request, ::hyperspace::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::ConfigUpdate, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Configure_, context, request, response);
}

void Database::Stub::async::Configure(::grpc::ClientContext* context, const ::hyperspace::ConfigUpdate* request, ::hyperspace::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::ConfigUpdate, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Configure_, context, request, response, std::move(f));
}

void Database::Stub::async::Configure(::grpc::ClientContext* context, const ::hyperspace::ConfigUpdate* request, ::hyperspace::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Configure_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::PrepareAsyncConfigureRaw(::grpc::ClientContext* context, const ::hyperspace::ConfigUpdate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::StatusResponse, ::hyperspace::ConfigUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Configure_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::AsyncConfigureRaw(::grpc::ClientContext* context, const ::hyperspace::ConfigUpdate& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConfigureRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::hyperspace::ReplicationLog>* Database::Stub::ReplicateRaw(::grpc::ClientContext* context, const ::hyperspace::ReplicationRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hyperspace::ReplicationLog>::Create(channel_.get(), rpcmethod_Replicate_, context, request);
}

void Database::Stub::async::Replicate(::grpc::ClientContext* context, const ::hyperspace::ReplicationRequest* request, ::grpc::ClientReadReactor< ::hyperspace::ReplicationLog>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hyperspace::ReplicationLog>::Create(stub_->channel_.get(), stub_->rpcmethod_Replicate_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hyperspace::ReplicationLog>* Database::Stub::AsyncReplicateRaw(::grpc::ClientContext* context, const ::hyperspace::ReplicationRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::ReplicationLog>::Create(channel_.get(), cq, rpcmethod_Replicate_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hyperspace::ReplicationLog>* Database::Stub::PrepareAsyncReplicateRaw(::grpc::ClientContext* context, const ::hyperspace::ReplicationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::ReplicationLog>::Create(channel_.get(), cq, rpcmethod_Replicate_, context, request, false, nullptr);
}

::grpc::ClientReader< ::hyperspace::EventMessage>* Database::Stub::SubscribeToEventsRaw(::grpc::ClientContext* context, const ::hyperspace::EventSubscriptionRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hyperspace::EventMessage>::Create(channel_.get(), rpcmethod_SubscribeToEvents_, context, request);
}

void Database::Stub::async::SubscribeToEvents(::grpc::ClientContext* context, const ::hyperspace::EventSubscriptionRequest* request, ::grpc::ClientReadReactor< ::hyperspace::EventMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hyperspace::EventMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeToEvents_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hyperspace::EventMessage>* Database::Stub::AsyncSubscribeToEventsRaw(::grpc::ClientContext* context, const ::hyperspace::EventSubscriptionRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::EventMessage>::Create(channel_.get(), cq, rpcmethod_SubscribeToEvents_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hyperspace::EventMessage>* Database::Stub::PrepareAsyncSubscribeToEventsRaw(::grpc::ClientContext* context, const ::hyperspace::EventSubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::EventMessage>::Create(channel_.get(), cq, rpcmethod_SubscribeToEvents_, context, request, false, nullptr);
}

::grpc::Status Database::Stub::GetDigest(::grpc::ClientContext* context, const ::hyperspace::DigestRequest& request, ::hyperspace::DigestResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::DigestRequest, ::hyperspace::DigestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDigest_, context, request, response);
}

void Database::Stub::async::GetDigest(::grpc::ClientContext* context, const ::hyperspace::DigestRequest* request, ::hyperspace::DigestResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::DigestRequest, ::hyperspace::DigestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDigest_, context, request, response, std::move(f));
}

void Database::Stub::async::GetDigest(::grpc::ClientContext* context, const ::hyperspace::DigestRequest* request, ::hyperspace::DigestResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDigest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::DigestResponse>* Database::Stub::PrepareAsyncGetDigestRaw(::grpc::ClientContext* context, const ::hyperspace::DigestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::DigestResponse, ::hyperspace::DigestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDigest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::DigestResponse>* Database::Stub::AsyncGetDigestRaw(::grpc::ClientContext* context, const ::hyperspace::DigestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDigestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::RebuildIndex(::grpc::ClientContext* context, const ::hyperspace::RebuildIndexRequest& request, ::hyperspace::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::RebuildIndexRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RebuildIndex_, context, request, response);
}

void Database::Stub::async::RebuildIndex(::grpc::ClientContext* context, const ::hyperspace::RebuildIndexRequest* request, ::hyperspace::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::RebuildIndexRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RebuildIndex_, context, request, response, std::move(f));
}

void Database::Stub::async::RebuildIndex(::grpc::ClientContext* context, const ::hyperspace::RebuildIndexRequest* request, ::hyperspace::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RebuildIndex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::PrepareAsyncRebuildIndexRaw(::grpc::ClientContext* context, const ::hyperspace::RebuildIndexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::StatusResponse, ::hyperspace::RebuildIndexRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RebuildIndex_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::StatusResponse>* Database::Stub::AsyncRebuildIndexRaw(::grpc::ClientContext* context, const ::hyperspace::RebuildIndexRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRebuildIndexRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Database::Stub::SyncHandshake(::grpc::ClientContext* context, const ::hyperspace::SyncHandshakeRequest& request, ::hyperspace::SyncHandshakeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hyperspace::SyncHandshakeRequest, ::hyperspace::SyncHandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SyncHandshake_, context, request, response);
}

void Database::Stub::async::SyncHandshake(::grpc::ClientContext* context, const ::hyperspace::SyncHandshakeRequest* request, ::hyperspace::SyncHandshakeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hyperspace::SyncHandshakeRequest, ::hyperspace::SyncHandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SyncHandshake_, context, request, response, std::move(f));
}

void Database::Stub::async::SyncHandshake(::grpc::ClientContext* context, const ::hyperspace::SyncHandshakeRequest* request, ::hyperspace::SyncHandshakeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SyncHandshake_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::SyncHandshakeResponse>* Database::Stub::PrepareAsyncSyncHandshakeRaw(::grpc::ClientContext* context, const ::hyperspace::SyncHandshakeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hyperspace::SyncHandshakeResponse, ::hyperspace::SyncHandshakeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SyncHandshake_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hyperspace::SyncHandshakeResponse>* Database::Stub::AsyncSyncHandshakeRaw(::grpc::ClientContext* context, const ::hyperspace::SyncHandshakeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSyncHandshakeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::hyperspace::SyncVectorData>* Database::Stub::SyncPullRaw(::grpc::ClientContext* context, const ::hyperspace::SyncPullRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::hyperspace::SyncVectorData>::Create(channel_.get(), rpcmethod_SyncPull_, context, request);
}

void Database::Stub::async::SyncPull(::grpc::ClientContext* context, const ::hyperspace::SyncPullRequest* request, ::grpc::ClientReadReactor< ::hyperspace::SyncVectorData>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hyperspace::SyncVectorData>::Create(stub_->channel_.get(), stub_->rpcmethod_SyncPull_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hyperspace::SyncVectorData>* Database::Stub::AsyncSyncPullRaw(::grpc::ClientContext* context, const ::hyperspace::SyncPullRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::SyncVectorData>::Create(channel_.get(), cq, rpcmethod_SyncPull_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hyperspace::SyncVectorData>* Database::Stub::PrepareAsyncSyncPullRaw(::grpc::ClientContext* context, const ::hyperspace::SyncPullRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hyperspace::SyncVectorData>::Create(channel_.get(), cq, rpcmethod_SyncPull_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::hyperspace::SyncVectorData>* Database::Stub::SyncPushRaw(::grpc::ClientContext* context, ::hyperspace::SyncPushResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::hyperspace::SyncVectorData>::Create(channel_.get(), rpcmethod_SyncPush_, context, response);
}

void Database::Stub::async::SyncPush(::grpc::ClientContext* context, ::hyperspace::SyncPushResponse* response, ::grpc::ClientWriteReactor< ::hyperspace::SyncVectorData>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::hyperspace::SyncVectorData>::Create(stub_->channel_.get(), stub_->rpcmethod_SyncPush_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::hyperspace::SyncVectorData>* Database::Stub::AsyncSyncPushRaw(::grpc::ClientContext* context, ::hyperspace::SyncPushResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::hyperspace::SyncVectorData>::Create(channel_.get(), cq, rpcmethod_SyncPush_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::hyperspace::SyncVectorData>* Database::Stub::PrepareAsyncSyncPushRaw(::grpc::ClientContext* context, ::hyperspace::SyncPushResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::hyperspace::SyncVectorData>::Create(channel_.get(), cq, rpcmethod_SyncPush_, context, response, false, nullptr);
}

Database::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::CreateCollectionRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::CreateCollectionRequest* req,
             ::hyperspace::StatusResponse* resp) {
               return service->CreateCollection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::DeleteCollectionRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::DeleteCollectionRequest* req,
             ::hyperspace::StatusResponse* resp) {
               return service->DeleteCollection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::Empty, ::hyperspace::ListCollectionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::Empty* req,
             ::hyperspace::ListCollectionsResponse* resp) {
               return service->ListCollections(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::CollectionStatsRequest, ::hyperspace::CollectionStatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::CollectionStatsRequest* req,
             ::hyperspace::CollectionStatsResponse* resp) {
               return service->GetCollectionStats(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::InsertRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::InsertRequest* req,
             ::hyperspace::InsertResponse* resp) {
               return service->Insert(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::BatchInsertRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::BatchInsertRequest* req,
             ::hyperspace::InsertResponse* resp) {
               return service->BatchInsert(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::InsertTextRequest, ::hyperspace::InsertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::InsertTextRequest* req,
             ::hyperspace::InsertResponse* resp) {
               return service->InsertText(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::DeleteRequest, ::hyperspace::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::DeleteRequest* req,
             ::hyperspace::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::SearchRequest, ::hyperspace::SearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::SearchRequest* req,
             ::hyperspace::SearchResponse* resp) {
               return service->Search(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::BatchSearchRequest, ::hyperspace::BatchSearchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::BatchSearchRequest* req,
             ::hyperspace::BatchSearchResponse* resp) {
               return service->SearchBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::GetNodeRequest, ::hyperspace::GraphNode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::GetNodeRequest* req,
             ::hyperspace::GraphNode* resp) {
               return service->GetNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::GetNeighborsRequest, ::hyperspace::GetNeighborsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::GetNeighborsRequest* req,
             ::hyperspace::GetNeighborsResponse* resp) {
               return service->GetNeighbors(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::GetConceptParentsRequest, ::hyperspace::GetConceptParentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::GetConceptParentsRequest* req,
             ::hyperspace::GetConceptParentsResponse* resp) {
               return service->GetConceptParents(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::TraverseRequest, ::hyperspace::TraverseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::TraverseRequest* req,
             ::hyperspace::TraverseResponse* resp) {
               return service->Traverse(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::FindSemanticClustersRequest, ::hyperspace::FindSemanticClustersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::FindSemanticClustersRequest* req,
             ::hyperspace::FindSemanticClustersResponse* resp) {
               return service->FindSemanticClusters(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[15],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Database::Service, ::hyperspace::MonitorRequest, ::hyperspace::SystemStats>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::MonitorRequest* req,
             ::grpc::ServerWriter<::hyperspace::SystemStats>* writer) {
               return service->Monitor(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::Empty, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::Empty* req,
             ::hyperspace::StatusResponse* resp) {
               return service->TriggerSnapshot(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::Empty, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::Empty* req,
             ::hyperspace::StatusResponse* resp) {
               return service->TriggerVacuum(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::ConfigUpdate, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::ConfigUpdate* req,
             ::hyperspace::StatusResponse* resp) {
               return service->Configure(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[19],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Database::Service, ::hyperspace::ReplicationRequest, ::hyperspace::ReplicationLog>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::ReplicationRequest* req,
             ::grpc::ServerWriter<::hyperspace::ReplicationLog>* writer) {
               return service->Replicate(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[20],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Database::Service, ::hyperspace::EventSubscriptionRequest, ::hyperspace::EventMessage>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::EventSubscriptionRequest* req,
             ::grpc::ServerWriter<::hyperspace::EventMessage>* writer) {
               return service->SubscribeToEvents(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::DigestRequest, ::hyperspace::DigestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::DigestRequest* req,
             ::hyperspace::DigestResponse* resp) {
               return service->GetDigest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[22],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::RebuildIndexRequest, ::hyperspace::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::RebuildIndexRequest* req,
             ::hyperspace::StatusResponse* resp) {
               return service->RebuildIndex(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[23],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Database::Service, ::hyperspace::SyncHandshakeRequest, ::hyperspace::SyncHandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::SyncHandshakeRequest* req,
             ::hyperspace::SyncHandshakeResponse* resp) {
               return service->SyncHandshake(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[24],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Database::Service, ::hyperspace::SyncPullRequest, ::hyperspace::SyncVectorData>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hyperspace::SyncPullRequest* req,
             ::grpc::ServerWriter<::hyperspace::SyncVectorData>* writer) {
               return service->SyncPull(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Database_method_names[25],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< Database::Service, ::hyperspace::SyncVectorData, ::hyperspace::SyncPushResponse>(
          [](Database::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::hyperspace::SyncVectorData>* reader,
             ::hyperspace::SyncPushResponse* resp) {
               return service->SyncPush(ctx, reader, resp);
             }, this)));
}

Database::Service::~Service() {
}

::grpc::Status Database::Service::CreateCollection(::grpc::ServerContext* context, const ::hyperspace::CreateCollectionRequest* request, ::hyperspace::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::DeleteCollection(::grpc::ServerContext* context, const ::hyperspace::DeleteCollectionRequest* request, ::hyperspace::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::ListCollections(::grpc::ServerContext* context, const ::hyperspace::Empty* request, ::hyperspace::ListCollectionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::GetCollectionStats(::grpc::ServerContext* context, const ::hyperspace::CollectionStatsRequest* request, ::hyperspace::CollectionStatsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::Insert(::grpc::ServerContext* context, const ::hyperspace::InsertRequest* request, ::hyperspace::InsertResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::BatchInsert(::grpc::ServerContext* context, const ::hyperspace::BatchInsertRequest* request, ::hyperspace::InsertResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::InsertText(::grpc::ServerContext* context, const ::hyperspace::InsertTextRequest* request, ::hyperspace::InsertResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::Delete(::grpc::ServerContext* context, const ::hyperspace::DeleteRequest* request, ::hyperspace::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::Search(::grpc::ServerContext* context, const ::hyperspace::SearchRequest* request, ::hyperspace::SearchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::SearchBatch(::grpc::ServerContext* context, const ::hyperspace::BatchSearchRequest* request, ::hyperspace::BatchSearchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::GetNode(::grpc::ServerContext* context, const ::hyperspace::GetNodeRequest* request, ::hyperspace::GraphNode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::GetNeighbors(::grpc::ServerContext* context, const ::hyperspace::GetNeighborsRequest* request, ::hyperspace::GetNeighborsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::GetConceptParents(::grpc::ServerContext* context, const ::hyperspace::GetConceptParentsRequest* request, ::hyperspace::GetConceptParentsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::Traverse(::grpc::ServerContext* context, const ::hyperspace::TraverseRequest* request, ::hyperspace::TraverseResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::FindSemanticClusters(::grpc::ServerContext* context, const ::hyperspace::FindSemanticClustersRequest* request, ::hyperspace::FindSemanticClustersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::Monitor(::grpc::ServerContext* context, const ::hyperspace::MonitorRequest* request, ::grpc::ServerWriter< ::hyperspace::SystemStats>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::TriggerSnapshot(::grpc::ServerContext* context, const ::hyperspace::Empty* request, ::hyperspace::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::TriggerVacuum(::grpc::ServerContext* context, const ::hyperspace::Empty* request, ::hyperspace::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::Configure(::grpc::ServerContext* context, const ::hyperspace::ConfigUpdate* request, ::hyperspace::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::Replicate(::grpc::ServerContext* context, const ::hyperspace::ReplicationRequest* request, ::grpc::ServerWriter< ::hyperspace::ReplicationLog>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::SubscribeToEvents(::grpc::ServerContext* context, const ::hyperspace::EventSubscriptionRequest* request, ::grpc::ServerWriter< ::hyperspace::EventMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::GetDigest(::grpc::ServerContext* context, const ::hyperspace::DigestRequest* request, ::hyperspace::DigestResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::RebuildIndex(::grpc::ServerContext* context, const ::hyperspace::RebuildIndexRequest* request, ::hyperspace::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::SyncHandshake(::grpc::ServerContext* context, const ::hyperspace::SyncHandshakeRequest* request, ::hyperspace::SyncHandshakeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::SyncPull(::grpc::ServerContext* context, const ::hyperspace::SyncPullRequest* request, ::grpc::ServerWriter< ::hyperspace::SyncVectorData>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Database::Service::SyncPush(::grpc::ServerContext* context, ::grpc::ServerReader< ::hyperspace::SyncVectorData>* reader, ::hyperspace::SyncPushResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hyperspace
#include <grpcpp/ports_undef.inc>

