// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: hyperspace.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Database_CreateCollection_FullMethodName     = "/hyperspace.Database/CreateCollection"
	Database_DeleteCollection_FullMethodName     = "/hyperspace.Database/DeleteCollection"
	Database_ListCollections_FullMethodName      = "/hyperspace.Database/ListCollections"
	Database_GetCollectionStats_FullMethodName   = "/hyperspace.Database/GetCollectionStats"
	Database_Insert_FullMethodName               = "/hyperspace.Database/Insert"
	Database_BatchInsert_FullMethodName          = "/hyperspace.Database/BatchInsert"
	Database_InsertText_FullMethodName           = "/hyperspace.Database/InsertText"
	Database_Delete_FullMethodName               = "/hyperspace.Database/Delete"
	Database_Search_FullMethodName               = "/hyperspace.Database/Search"
	Database_SearchBatch_FullMethodName          = "/hyperspace.Database/SearchBatch"
	Database_GetNode_FullMethodName              = "/hyperspace.Database/GetNode"
	Database_GetNeighbors_FullMethodName         = "/hyperspace.Database/GetNeighbors"
	Database_GetConceptParents_FullMethodName    = "/hyperspace.Database/GetConceptParents"
	Database_Traverse_FullMethodName             = "/hyperspace.Database/Traverse"
	Database_FindSemanticClusters_FullMethodName = "/hyperspace.Database/FindSemanticClusters"
	Database_Monitor_FullMethodName              = "/hyperspace.Database/Monitor"
	Database_TriggerSnapshot_FullMethodName      = "/hyperspace.Database/TriggerSnapshot"
	Database_TriggerVacuum_FullMethodName        = "/hyperspace.Database/TriggerVacuum"
	Database_Configure_FullMethodName            = "/hyperspace.Database/Configure"
	Database_Replicate_FullMethodName            = "/hyperspace.Database/Replicate"
	Database_SubscribeToEvents_FullMethodName    = "/hyperspace.Database/SubscribeToEvents"
	Database_GetDigest_FullMethodName            = "/hyperspace.Database/GetDigest"
	Database_RebuildIndex_FullMethodName         = "/hyperspace.Database/RebuildIndex"
	Database_SyncHandshake_FullMethodName        = "/hyperspace.Database/SyncHandshake"
	Database_SyncPull_FullMethodName             = "/hyperspace.Database/SyncPull"
	Database_SyncPush_FullMethodName             = "/hyperspace.Database/SyncPush"
)

// DatabaseClient is the client API for Database service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabaseClient interface {
	// Collection Management
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	GetCollectionStats(ctx context.Context, in *CollectionStatsRequest, opts ...grpc.CallOption) (*CollectionStatsResponse, error)
	// Insert vectors
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	BatchInsert(ctx context.Context, in *BatchInsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	InsertText(ctx context.Context, in *InsertTextRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// Delete vectors
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Search (ANN)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Batch Search (ANN)
	SearchBatch(ctx context.Context, in *BatchSearchRequest, opts ...grpc.CallOption) (*BatchSearchResponse, error)
	// Graph Traversal API (v2.3)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GraphNode, error)
	GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error)
	GetConceptParents(ctx context.Context, in *GetConceptParentsRequest, opts ...grpc.CallOption) (*GetConceptParentsResponse, error)
	Traverse(ctx context.Context, in *TraverseRequest, opts ...grpc.CallOption) (*TraverseResponse, error)
	FindSemanticClusters(ctx context.Context, in *FindSemanticClustersRequest, opts ...grpc.CallOption) (*FindSemanticClustersResponse, error)
	// Stream statistics for TUI (Global or Collection tailored)
	Monitor(ctx context.Context, in *MonitorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStats], error)
	// Admin Controls
	TriggerSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	TriggerVacuum(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	// Dynamic Configuration
	Configure(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*StatusResponse, error)
	// Replication (Leader -> Follower)
	Replicate(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplicationLog], error)
	// CDC/Event Stream (External subscribers)
	SubscribeToEvents(ctx context.Context, in *EventSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventMessage], error)
	GetDigest(ctx context.Context, in *DigestRequest, opts ...grpc.CallOption) (*DigestResponse, error)
	RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Delta Sync (Merkle Tree — Task 2.1)
	// Step 1: Client sends its digest, server returns which buckets differ.
	SyncHandshake(ctx context.Context, in *SyncHandshakeRequest, opts ...grpc.CallOption) (*SyncHandshakeResponse, error)
	// Step 2: Client requests vectors from specific buckets, server streams them.
	SyncPull(ctx context.Context, in *SyncPullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncVectorData], error)
	// Step 3 (optional): Client pushes its unique vectors to the server.
	SyncPush(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncVectorData, SyncPushResponse], error)
}

type databaseClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseClient(cc grpc.ClientConnInterface) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Database_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Database_DeleteCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, Database_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetCollectionStats(ctx context.Context, in *CollectionStatsRequest, opts ...grpc.CallOption) (*CollectionStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionStatsResponse)
	err := c.cc.Invoke(ctx, Database_GetCollectionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, Database_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) BatchInsert(ctx context.Context, in *BatchInsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, Database_BatchInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) InsertText(ctx context.Context, in *InsertTextRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, Database_InsertText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Database_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Database_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) SearchBatch(ctx context.Context, in *BatchSearchRequest, opts ...grpc.CallOption) (*BatchSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSearchResponse)
	err := c.cc.Invoke(ctx, Database_SearchBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GraphNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphNode)
	err := c.cc.Invoke(ctx, Database_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNeighborsResponse)
	err := c.cc.Invoke(ctx, Database_GetNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetConceptParents(ctx context.Context, in *GetConceptParentsRequest, opts ...grpc.CallOption) (*GetConceptParentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConceptParentsResponse)
	err := c.cc.Invoke(ctx, Database_GetConceptParents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Traverse(ctx context.Context, in *TraverseRequest, opts ...grpc.CallOption) (*TraverseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraverseResponse)
	err := c.cc.Invoke(ctx, Database_Traverse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) FindSemanticClusters(ctx context.Context, in *FindSemanticClustersRequest, opts ...grpc.CallOption) (*FindSemanticClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindSemanticClustersResponse)
	err := c.cc.Invoke(ctx, Database_FindSemanticClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Monitor(ctx context.Context, in *MonitorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Database_ServiceDesc.Streams[0], Database_Monitor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MonitorRequest, SystemStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_MonitorClient = grpc.ServerStreamingClient[SystemStats]

func (c *databaseClient) TriggerSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Database_TriggerSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) TriggerVacuum(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Database_TriggerVacuum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Configure(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Database_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Replicate(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplicationLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Database_ServiceDesc.Streams[1], Database_Replicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicationRequest, ReplicationLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_ReplicateClient = grpc.ServerStreamingClient[ReplicationLog]

func (c *databaseClient) SubscribeToEvents(ctx context.Context, in *EventSubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Database_ServiceDesc.Streams[2], Database_SubscribeToEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventSubscriptionRequest, EventMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_SubscribeToEventsClient = grpc.ServerStreamingClient[EventMessage]

func (c *databaseClient) GetDigest(ctx context.Context, in *DigestRequest, opts ...grpc.CallOption) (*DigestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DigestResponse)
	err := c.cc.Invoke(ctx, Database_GetDigest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Database_RebuildIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) SyncHandshake(ctx context.Context, in *SyncHandshakeRequest, opts ...grpc.CallOption) (*SyncHandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncHandshakeResponse)
	err := c.cc.Invoke(ctx, Database_SyncHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) SyncPull(ctx context.Context, in *SyncPullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncVectorData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Database_ServiceDesc.Streams[3], Database_SyncPull_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncPullRequest, SyncVectorData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_SyncPullClient = grpc.ServerStreamingClient[SyncVectorData]

func (c *databaseClient) SyncPush(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncVectorData, SyncPushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Database_ServiceDesc.Streams[4], Database_SyncPush_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncVectorData, SyncPushResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_SyncPushClient = grpc.ClientStreamingClient[SyncVectorData, SyncPushResponse]

// DatabaseServer is the server API for Database service.
// All implementations must embed UnimplementedDatabaseServer
// for forward compatibility.
type DatabaseServer interface {
	// Collection Management
	CreateCollection(context.Context, *CreateCollectionRequest) (*StatusResponse, error)
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*StatusResponse, error)
	ListCollections(context.Context, *Empty) (*ListCollectionsResponse, error)
	GetCollectionStats(context.Context, *CollectionStatsRequest) (*CollectionStatsResponse, error)
	// Insert vectors
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	BatchInsert(context.Context, *BatchInsertRequest) (*InsertResponse, error)
	InsertText(context.Context, *InsertTextRequest) (*InsertResponse, error)
	// Delete vectors
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Search (ANN)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Batch Search (ANN)
	SearchBatch(context.Context, *BatchSearchRequest) (*BatchSearchResponse, error)
	// Graph Traversal API (v2.3)
	GetNode(context.Context, *GetNodeRequest) (*GraphNode, error)
	GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error)
	GetConceptParents(context.Context, *GetConceptParentsRequest) (*GetConceptParentsResponse, error)
	Traverse(context.Context, *TraverseRequest) (*TraverseResponse, error)
	FindSemanticClusters(context.Context, *FindSemanticClustersRequest) (*FindSemanticClustersResponse, error)
	// Stream statistics for TUI (Global or Collection tailored)
	Monitor(*MonitorRequest, grpc.ServerStreamingServer[SystemStats]) error
	// Admin Controls
	TriggerSnapshot(context.Context, *Empty) (*StatusResponse, error)
	TriggerVacuum(context.Context, *Empty) (*StatusResponse, error)
	// Dynamic Configuration
	Configure(context.Context, *ConfigUpdate) (*StatusResponse, error)
	// Replication (Leader -> Follower)
	Replicate(*ReplicationRequest, grpc.ServerStreamingServer[ReplicationLog]) error
	// CDC/Event Stream (External subscribers)
	SubscribeToEvents(*EventSubscriptionRequest, grpc.ServerStreamingServer[EventMessage]) error
	GetDigest(context.Context, *DigestRequest) (*DigestResponse, error)
	RebuildIndex(context.Context, *RebuildIndexRequest) (*StatusResponse, error)
	// Delta Sync (Merkle Tree — Task 2.1)
	// Step 1: Client sends its digest, server returns which buckets differ.
	SyncHandshake(context.Context, *SyncHandshakeRequest) (*SyncHandshakeResponse, error)
	// Step 2: Client requests vectors from specific buckets, server streams them.
	SyncPull(*SyncPullRequest, grpc.ServerStreamingServer[SyncVectorData]) error
	// Step 3 (optional): Client pushes its unique vectors to the server.
	SyncPush(grpc.ClientStreamingServer[SyncVectorData, SyncPushResponse]) error
	mustEmbedUnimplementedDatabaseServer()
}

// UnimplementedDatabaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseServer struct{}

func (UnimplementedDatabaseServer) CreateCollection(context.Context, *CreateCollectionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedDatabaseServer) DeleteCollection(context.Context, *DeleteCollectionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCollection not implemented")
}
func (UnimplementedDatabaseServer) ListCollections(context.Context, *Empty) (*ListCollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedDatabaseServer) GetCollectionStats(context.Context, *CollectionStatsRequest) (*CollectionStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionStats not implemented")
}
func (UnimplementedDatabaseServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedDatabaseServer) BatchInsert(context.Context, *BatchInsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsert not implemented")
}
func (UnimplementedDatabaseServer) InsertText(context.Context, *InsertTextRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertText not implemented")
}
func (UnimplementedDatabaseServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDatabaseServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDatabaseServer) SearchBatch(context.Context, *BatchSearchRequest) (*BatchSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchBatch not implemented")
}
func (UnimplementedDatabaseServer) GetNode(context.Context, *GetNodeRequest) (*GraphNode, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedDatabaseServer) GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNeighbors not implemented")
}
func (UnimplementedDatabaseServer) GetConceptParents(context.Context, *GetConceptParentsRequest) (*GetConceptParentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConceptParents not implemented")
}
func (UnimplementedDatabaseServer) Traverse(context.Context, *TraverseRequest) (*TraverseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Traverse not implemented")
}
func (UnimplementedDatabaseServer) FindSemanticClusters(context.Context, *FindSemanticClustersRequest) (*FindSemanticClustersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindSemanticClusters not implemented")
}
func (UnimplementedDatabaseServer) Monitor(*MonitorRequest, grpc.ServerStreamingServer[SystemStats]) error {
	return status.Error(codes.Unimplemented, "method Monitor not implemented")
}
func (UnimplementedDatabaseServer) TriggerSnapshot(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSnapshot not implemented")
}
func (UnimplementedDatabaseServer) TriggerVacuum(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerVacuum not implemented")
}
func (UnimplementedDatabaseServer) Configure(context.Context, *ConfigUpdate) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedDatabaseServer) Replicate(*ReplicationRequest, grpc.ServerStreamingServer[ReplicationLog]) error {
	return status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedDatabaseServer) SubscribeToEvents(*EventSubscriptionRequest, grpc.ServerStreamingServer[EventMessage]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToEvents not implemented")
}
func (UnimplementedDatabaseServer) GetDigest(context.Context, *DigestRequest) (*DigestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDigest not implemented")
}
func (UnimplementedDatabaseServer) RebuildIndex(context.Context, *RebuildIndexRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildIndex not implemented")
}
func (UnimplementedDatabaseServer) SyncHandshake(context.Context, *SyncHandshakeRequest) (*SyncHandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncHandshake not implemented")
}
func (UnimplementedDatabaseServer) SyncPull(*SyncPullRequest, grpc.ServerStreamingServer[SyncVectorData]) error {
	return status.Error(codes.Unimplemented, "method SyncPull not implemented")
}
func (UnimplementedDatabaseServer) SyncPush(grpc.ClientStreamingServer[SyncVectorData, SyncPushResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncPush not implemented")
}
func (UnimplementedDatabaseServer) mustEmbedUnimplementedDatabaseServer() {}
func (UnimplementedDatabaseServer) testEmbeddedByValue()                  {}

// UnsafeDatabaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseServer will
// result in compilation errors.
type UnsafeDatabaseServer interface {
	mustEmbedUnimplementedDatabaseServer()
}

func RegisterDatabaseServer(s grpc.ServiceRegistrar, srv DatabaseServer) {
	// If the following call panics, it indicates UnimplementedDatabaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Database_ServiceDesc, srv)
}

func _Database_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_DeleteCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).DeleteCollection(ctx, req.(*DeleteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).ListCollections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetCollectionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetCollectionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_GetCollectionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetCollectionStats(ctx, req.(*CollectionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_BatchInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).BatchInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_BatchInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).BatchInsert(ctx, req.(*BatchInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_InsertText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).InsertText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_InsertText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).InsertText(ctx, req.(*InsertTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_SearchBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).SearchBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_SearchBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).SearchBatch(ctx, req.(*BatchSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_GetNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetNeighbors(ctx, req.(*GetNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetConceptParents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConceptParentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetConceptParents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_GetConceptParents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetConceptParents(ctx, req.(*GetConceptParentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Traverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Traverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_Traverse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Traverse(ctx, req.(*TraverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_FindSemanticClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSemanticClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).FindSemanticClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_FindSemanticClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).FindSemanticClusters(ctx, req.(*FindSemanticClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Monitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatabaseServer).Monitor(m, &grpc.GenericServerStream[MonitorRequest, SystemStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_MonitorServer = grpc.ServerStreamingServer[SystemStats]

func _Database_TriggerSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).TriggerSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_TriggerSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).TriggerSnapshot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_TriggerVacuum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).TriggerVacuum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_TriggerVacuum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).TriggerVacuum(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Configure(ctx, req.(*ConfigUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplicationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatabaseServer).Replicate(m, &grpc.GenericServerStream[ReplicationRequest, ReplicationLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_ReplicateServer = grpc.ServerStreamingServer[ReplicationLog]

func _Database_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventSubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatabaseServer).SubscribeToEvents(m, &grpc.GenericServerStream[EventSubscriptionRequest, EventMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_SubscribeToEventsServer = grpc.ServerStreamingServer[EventMessage]

func _Database_GetDigest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DigestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetDigest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_GetDigest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetDigest(ctx, req.(*DigestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_RebuildIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).RebuildIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_RebuildIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).RebuildIndex(ctx, req.(*RebuildIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_SyncHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncHandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).SyncHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Database_SyncHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).SyncHandshake(ctx, req.(*SyncHandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_SyncPull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncPullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DatabaseServer).SyncPull(m, &grpc.GenericServerStream[SyncPullRequest, SyncVectorData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_SyncPullServer = grpc.ServerStreamingServer[SyncVectorData]

func _Database_SyncPush_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DatabaseServer).SyncPush(&grpc.GenericServerStream[SyncVectorData, SyncPushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Database_SyncPushServer = grpc.ClientStreamingServer[SyncVectorData, SyncPushResponse]

// Database_ServiceDesc is the grpc.ServiceDesc for Database service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Database_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperspace.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _Database_CreateCollection_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _Database_DeleteCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _Database_ListCollections_Handler,
		},
		{
			MethodName: "GetCollectionStats",
			Handler:    _Database_GetCollectionStats_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _Database_Insert_Handler,
		},
		{
			MethodName: "BatchInsert",
			Handler:    _Database_BatchInsert_Handler,
		},
		{
			MethodName: "InsertText",
			Handler:    _Database_InsertText_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Database_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Database_Search_Handler,
		},
		{
			MethodName: "SearchBatch",
			Handler:    _Database_SearchBatch_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Database_GetNode_Handler,
		},
		{
			MethodName: "GetNeighbors",
			Handler:    _Database_GetNeighbors_Handler,
		},
		{
			MethodName: "GetConceptParents",
			Handler:    _Database_GetConceptParents_Handler,
		},
		{
			MethodName: "Traverse",
			Handler:    _Database_Traverse_Handler,
		},
		{
			MethodName: "FindSemanticClusters",
			Handler:    _Database_FindSemanticClusters_Handler,
		},
		{
			MethodName: "TriggerSnapshot",
			Handler:    _Database_TriggerSnapshot_Handler,
		},
		{
			MethodName: "TriggerVacuum",
			Handler:    _Database_TriggerVacuum_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Database_Configure_Handler,
		},
		{
			MethodName: "GetDigest",
			Handler:    _Database_GetDigest_Handler,
		},
		{
			MethodName: "RebuildIndex",
			Handler:    _Database_RebuildIndex_Handler,
		},
		{
			MethodName: "SyncHandshake",
			Handler:    _Database_SyncHandshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Monitor",
			Handler:       _Database_Monitor_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Replicate",
			Handler:       _Database_Replicate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _Database_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncPull",
			Handler:       _Database_SyncPull_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncPush",
			Handler:       _Database_SyncPush_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "hyperspace.proto",
}
